import { CLINE_SYSTEM_PROMPT_ACT_MODE } from "./act";
import { CLINE_SYSTEM_PROMPT_YOLO_MODE } from "./yolo";

export const DEFAULT_CLINE_SYSTEM_PROMPTS = {
	ACT: CLINE_SYSTEM_PROMPT_ACT_MODE,
	YOLO: CLINE_SYSTEM_PROMPT_YOLO_MODE,
};

export const DEFAULT_CLINE_SYSTEM_PROMPT = CLINE_SYSTEM_PROMPT_ACT_MODE;

export const DEFAULT_ZECK_SYSTEM_PROMPTS = DEFAULT_CLINE_SYSTEM_PROMPTS;
export const DEFAULT_ZECK_SYSTEM_PROMPT = DEFAULT_CLINE_SYSTEM_PROMPT;
